project:
  type: book

book:
  title: "ds6400-portfolio"
  author: "Christina Kosti"
  date: "8/27/2026"
  chapters:
    - index.qmd
    - 01-cross-validation-selection-bias.qmd
    - 02-632-plus-bootstrap.qmd

format:
  html:
    theme:
      - cosmo
  pdf:
    documentclass: scrreprt

editor: visual

