<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; Performance Measures – ds6400-portfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-631496449bf32ff9b0bb69a6bfd9195d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-performance-measures.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Performance Measures</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ds6400-portfolio</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-performance-measures.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Performance Measures</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#varma-simon-2006" id="toc-varma-simon-2006" class="nav-link active" data-scroll-target="#varma-simon-2006"><span class="header-section-number">1.1</span> Varma &amp; Simon (2006)</a>
  <ul class="collapse">
  <li><a href="#problem" id="toc-problem" class="nav-link" data-scroll-target="#problem"><span class="header-section-number">1.1.1</span> Problem</a></li>
  <li><a href="#why-does-the-bias-happen" id="toc-why-does-the-bias-happen" class="nav-link" data-scroll-target="#why-does-the-bias-happen"><span class="header-section-number">1.1.2</span> Why does the bias happen?</a></li>
  <li><a href="#what-do-the-authors-propose-instead" id="toc-what-do-the-authors-propose-instead" class="nav-link" data-scroll-target="#what-do-the-authors-propose-instead"><span class="header-section-number">1.1.3</span> What do the authors propose instead?</a></li>
  <li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design"><span class="header-section-number">1.1.4</span> Study design</a></li>
  <li><a href="#classifier-implementation" id="toc-classifier-implementation" class="nav-link" data-scroll-target="#classifier-implementation"><span class="header-section-number">1.1.5</span> Classifier implementation</a></li>
  <li><a href="#nested-cross-validation-implementation" id="toc-nested-cross-validation-implementation" class="nav-link" data-scroll-target="#nested-cross-validation-implementation"><span class="header-section-number">1.1.6</span> Nested cross-validation implementation</a></li>
  <li><a href="#main-findings" id="toc-main-findings" class="nav-link" data-scroll-target="#main-findings"><span class="header-section-number">1.1.7</span> Main findings</a></li>
  <li><a href="#main-conclusion-stop-doing-x-start-doing-y" id="toc-main-conclusion-stop-doing-x-start-doing-y" class="nav-link" data-scroll-target="#main-conclusion-stop-doing-x-start-doing-y"><span class="header-section-number">1.1.8</span> Main conclusion: stop doing X, start doing Y</a></li>
  <li><a href="#proposed-computational-exploration" id="toc-proposed-computational-exploration" class="nav-link" data-scroll-target="#proposed-computational-exploration"><span class="header-section-number">1.1.9</span> Proposed computational exploration</a></li>
  <li><a href="#planned-figure" id="toc-planned-figure" class="nav-link" data-scroll-target="#planned-figure"><span class="header-section-number">1.1.10</span> Planned figure</a></li>
  <li><a href="#computational-exploration" id="toc-computational-exploration" class="nav-link" data-scroll-target="#computational-exploration"><span class="header-section-number">1.1.11</span> Computational exploration</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">1.1.12</span> Conclusions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Performance Measures</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="varma-simon-2006" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="varma-simon-2006"><span class="header-section-number">1.1</span> Varma &amp; Simon (2006)</h2>
<p><strong>Title:</strong> Bias in error estimation when using cross-validation for model selection<br>
<strong>Journal:</strong> BMC Bioinformatics</p>
<section id="problem" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="problem"><span class="header-section-number">1.1.1</span> Problem</h3>
<p>Cross-validation (CV) can be used to estimate how well a classifier will perform on independent data. However, ordinary CV can become biased when the same CV procedure is used both to choose the best model settings and to estimate the performance of the resulting model.</p>
</section>
<section id="why-does-the-bias-happen" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="why-does-the-bias-happen"><span class="header-section-number">1.1.2</span> Why does the bias happen?</h3>
<p>Choosing classifier parameters is part of the model training process. When several parameter values are tested using cross-validation, the value with the lowest CV error is selected. Because this minimum is chosen from several CV estimates, it may be too optimistic and underestimate the true prediction error. The authors call this parameter selection bias.</p>
</section>
<section id="what-do-the-authors-propose-instead" class="level3" data-number="1.1.3">
<h3 data-number="1.1.3" class="anchored" data-anchor-id="what-do-the-authors-propose-instead"><span class="header-section-number">1.1.3</span> What do the authors propose instead?</h3>
<p>The classifier parameter tuning should be treated as part of the model training procedure and therefore repeated inside the cross-validation process.</p>
<p>They use nested cross-validation, which contains two CV loops:</p>
<ul>
<li><strong>Inner CV:</strong> selects the optimal classifier parameters.</li>
<li><strong>Outer CV:</strong> estimates the prediction error of the tuned classifier.</li>
</ul>
<p>This separates model tuning from model evaluation and reduces the bias in the estimated prediction error.</p>
</section>
<section id="study-design" class="level3" data-number="1.1.4">
<h3 data-number="1.1.4" class="anchored" data-anchor-id="study-design"><span class="header-section-number">1.1.4</span> Study design</h3>
<p>A simulation study was used so they could compare the estimated prediction error with the true error.</p>
<p>The authors generated at least 1,000 simulated datasets each containing:</p>
<ul>
<li>40 samples</li>
<li>20 samples in class 1 and 20 in class 2</li>
<li>6,000 simulated gene-expression features</li>
</ul>
<p>They considered two types of datasets:</p>
<ul>
<li><strong>Null datasets:</strong> there was no true difference between the two classes, so classification should perform at about chance level.</li>
<li><strong>Non-null datasets:</strong> 10 of the 6,000 features had a true difference between the classes, so there was some real predictive signal.</li>
</ul>
<p>They then applied the classification and cross-validation procedures to these simulated datasets and compared the estimated errors with performance on independent test data.</p>
</section>
<section id="classifier-implementation" class="level3" data-number="1.1.5">
<h3 data-number="1.1.5" class="anchored" data-anchor-id="classifier-implementation"><span class="header-section-number">1.1.5</span> Classifier implementation</h3>
<section id="shrunken-centroids" class="level4" data-number="1.1.5.1">
<h4 data-number="1.1.5.1" class="anchored" data-anchor-id="shrunken-centroids"><span class="header-section-number">1.1.5.1</span> Shrunken Centroids</h4>
<p>For the Shrunken Centroids classifier, the authors varied the tuning parameter Δ between 0.01 and 1. For each value of Δ, they calculated the 10-fold CV error and selected the value with the minimum error.</p>
<p><span class="math display">\[
\Delta^* = \arg\min_{\Delta} CV(\Delta)
\]</span></p>
<p>They then trained the optimized classifier on all 40 training samples using the selected Δ* and tested it on 20,000 independent samples to estimate its true prediction error.</p>
</section>
<section id="support-vector-machine-svm" class="level4" data-number="1.1.5.2">
<h4 data-number="1.1.5.2" class="anchored" data-anchor-id="support-vector-machine-svm"><span class="header-section-number">1.1.5.2</span> Support Vector Machine (SVM)</h4>
<p>For the SVM, they tuned two parameters, C and γ. They used Leave-One-Out Cross-Validation (LOOCV) to calculate the prediction error for different combinations of these parameters and selected the combination with the minimum LOOCV error.</p>
<p><span class="math display">\[
(C^*, \gamma^*) = \arg\min_{C,\gamma} CV(C,\gamma)
\]</span></p>
<p>The optimized SVM was then trained on all 40 samples and evaluated on 20,000 independent test samples to estimate the true error.</p>
</section>
</section>
<section id="nested-cross-validation-implementation" class="level3" data-number="1.1.6">
<h3 data-number="1.1.6" class="anchored" data-anchor-id="nested-cross-validation-implementation"><span class="header-section-number">1.1.6</span> Nested cross-validation implementation</h3>
<p>A nested cross-validation procedure was then evaluated in which the parameter-tuning step was repeated inside an outer CV loop.</p>
<p>For the Shrunken Centroids classifier, one sample was left out from the 40-sample dataset. The remaining 39 samples were used to select the optimal value of Δ using 10-fold CV. The classifier was then trained on those 39 samples using the selected Δ and used to predict the class of the one sample that had been left out.</p>
<p>This process was repeated until each of the 40 samples had been left out once. The average error across the 40 outer predictions was used as the nested CV error estimate.</p>
<p>The same nested-CV principle was also applied to the optimized SVM classifier.</p>
<p>In this setup the inner CV loop is used for parameter tuning and the outer CV loop is used to estimate prediction error.</p>
</section>
<section id="main-findings" class="level3" data-number="1.1.7">
<h3 data-number="1.1.7" class="anchored" data-anchor-id="main-findings"><span class="header-section-number">1.1.7</span> Main findings</h3>
<p>For the null datasets, the true prediction error was approximately 50%, because there was no real difference between the two classes.</p>
<p>However, after tuning the classifiers, the average CV error estimates were lower than the true error:</p>
<ul>
<li>Shrunken Centroids: mean CV error = 37.8%</li>
<li>SVM: mean CV error = 41.7%</li>
<li>True error for both classifiers = 50.0%</li>
</ul>
<p>This shows that using the minimum CV error after parameter tuning made the classifiers appear more accurate than they really were on independent data.</p>
<p>Figure 1 shows this bias for the optimized Shrunken Centroids classifier.</p>
<p><img src="images/A-Fig1.png" class="img-fluid" alt="Figure 1 from Varma and Simon (2006)"></p>
<p><em>Source: Varma &amp; Simon (2006), Figure 1.</em></p>
<p>Nested cross-validation produced error estimates that were much closer to the true error.</p>
<p>For the Shrunken Centroids classifier on null data:</p>
<ul>
<li>Nested CV error = 54.2%</li>
<li>True error = 50.0%</li>
</ul>
<p><img src="images/A-Fig3.png" class="img-fluid" alt="Figure 3 from Varma and Simon (2006)"></p>
<p><em>Source: Varma &amp; Simon (2006), Figure 3.</em></p>
<p>For the SVM classifier on non-null data:</p>
<ul>
<li>Nested CV error = 35.3%</li>
<li>True error = 32.0%</li>
</ul>
<p>Their results showed that nested CV substantially reduced the bias in the estimated prediction error.</p>
</section>
<section id="main-conclusion-stop-doing-x-start-doing-y" class="level3" data-number="1.1.8">
<h3 data-number="1.1.8" class="anchored" data-anchor-id="main-conclusion-stop-doing-x-start-doing-y"><span class="header-section-number">1.1.8</span> Main conclusion: stop doing X, start doing Y</h3>
<p><strong>Stop:</strong> using the minimum cross-validation error obtained during parameter tuning as the final estimate of how well the optimized classifier will perform on independent data.</p>
<p><strong>Start:</strong> treat parameter tuning as part of the training process and use nested cross-validation, where the inner CV loop tunes the classifier and the outer CV loop estimates prediction error.</p>
<p>Takeaway: Nested CV provides an almost unbiased estimate of the true error of an optimized classifier.</p>
</section>
<section id="proposed-computational-exploration" class="level3" data-number="1.1.9">
<h3 data-number="1.1.9" class="anchored" data-anchor-id="proposed-computational-exploration"><span class="header-section-number">1.1.9</span> Proposed computational exploration</h3>
<p>For my computational exploration, I plan to develop a simpler simulation that demonstrates the parameter-selection bias described in the paper.</p>
<p>I will simulate a binary classification problem with two equally sized classes and no true difference in the predictor distributions between the classes. Therefore, the true classification error should be approximately 50%.</p>
<p>I will use a k-nearest neighbors (kNN) classifier and treat the number of neighbors, k, as the tuning parameter. Each simulated training dataset will contain 40 observations, with 20 observations in each class. I will compare several candidate values of k (for example, 1, 3, 5, 7, and 9). Then, I will:</p>
<ol type="1">
<li>Generate a training dataset of 40 observations from two equally sized classes with no true difference in their predictor distributions.</li>
<li>Use 10-fold cross-validation to compare several values of k and select the value with the lowest CV error.</li>
<li>Record this minimum CV error.</li>
<li>Use nested cross-validation with 10-fold CV in the inner loop to select k and LOOCV in the outer loop to estimate prediction error.</li>
<li>Select k using 10-fold CV on the full training dataset, train the optimized classifier on all 40 observations, and evaluate it on a large independently simulated test dataset to approximate the true prediction error.</li>
<li>Repeat the simulation 500 times and compare the distributions of the three error estimates.</li>
</ol>
<p>The main question will be whether the minimum CV error after tuning systematically underestimates the true prediction error, and whether nested CV produces an estimate closer to the truth.</p>
</section>
<section id="planned-figure" class="level3" data-number="1.1.10">
<h3 data-number="1.1.10" class="anchored" data-anchor-id="planned-figure"><span class="header-section-number">1.1.10</span> Planned figure</h3>
<p>I plan to create a figure comparing the prediction-error estimates obtained from:</p>
<ol type="1">
<li>Minimum CV error after tuning</li>
<li>Nested CV</li>
<li>Independent test-set error</li>
</ol>
<p>The figure will summarize the distribution of these errors across repeated simulations.</p>
<p>Because the simulated data will contain no true class difference, the independent test-set error should be approximately 50%. A persuasive result would show that the minimum CV error after tuning tends to underestimate this true error, while the nested-CV error remains closer to it.</p>
</section>
<section id="computational-exploration" class="level3" data-number="1.1.11">
<h3 data-number="1.1.11" class="anchored" data-anchor-id="computational-exploration"><span class="header-section-number">1.1.11</span> Computational exploration</h3>
<section id="phase-1-simulating-the-data" class="level4" data-number="1.1.11.1">
<h4 data-number="1.1.11.1" class="anchored" data-anchor-id="phase-1-simulating-the-data"><span class="header-section-number">1.1.11.1</span> Phase 1: Simulating the data</h4>
<p>I first simulate a binary classification problem with 40 observations that are equally divided between classes A and B. The two predictors are generated from the same distribution for both classes, so they contain no true information about class membership. This creates a null setting in which the expected classification error is approximately 50%.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>), <span class="at">each =</span> <span class="dv">20</span>)) <span class="co"># Creates 40 class labels: 20 A and 20 B</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(class)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>class
 A  B 
20 20 </code></pre>
</div>
</div>
<p>The class counts confirm that the simulated dataset is balanced, with 20 observations in class A and 20 in class B.</p>
<p>Next, I generate two continuous predictors, <code>x1</code> and <code>x2</code>, from a standard normal distribution with mean 0 and standard deviation 1. Because both classes use the same distribution, the predictors contain no true class information and any apparent separation is due to chance.</p>
<p>Mathematically, for each predictor <span class="math inline">\(j=1,2\)</span>,</p>
<p><span class="math display">\[
X_{ij} \mid Y_i=A \sim N(0,1)
\qquad \text{and} \qquad
X_{ij} \mid Y_i=B \sim N(0,1).
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># Keeps data reproducible</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">40</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>) <span class="co"># Generates one x1 value per observation from N(0,1)</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">40</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>) <span class="co"># Generates one x2 value per observation from N(0,1)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Each observation can now be represented by its predictor vector <span class="math inline">\(\mathbf{X}_i\)</span> and class label <span class="math inline">\(Y_i\)</span>, where</p>
<p><span class="math display">\[
\mathbf{X}_i = (X_{i1}, X_{i2}) \in \mathbb{R}^2,
\qquad
Y_i \in \{A,B\}.
\]</span></p>
<p>Here, <span class="math inline">\(\mathbf{X}_i\)</span> contains the two predictor values for observation <span class="math inline">\(i\)</span>, while <span class="math inline">\(Y_i\)</span> indicates whether that observation belongs to class A or B. The full simulated dataset, denoted by <span class="math inline">\(\mathcal{D}\)</span>, can therefore be written as</p>
<p><span class="math display">\[
\mathcal{D} = \{(\mathbf{X}_i, Y_i)\}_{i=1}^{40}.
\]</span></p>
<p>I combine these values into a data frame so that each row represents one simulated observation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">class =</span> class,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x1 =</span> x1,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x2 =</span> x2</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>) <span class="co"># Creates the simulated data frame</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>At this point, each of the 40 observations has a class label and two predictor values, but the predictors were generated independently of class.</p>
<p>To visualize the null setting, I plot <code>x1</code> against <code>x2</code> and distinguish the two classes by color.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  sim_data<span class="sc">$</span>x1,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  sim_data<span class="sc">$</span>x2,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"steelblue"</span>, <span class="st">"tomato"</span>)[sim_data<span class="sc">$</span>class],</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex =</span> <span class="fl">1.2</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Predictor x1"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Predictor x2"</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Null Simulation: No True Class Separation"</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"topright"</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Class A"</span>, <span class="st">"Class B"</span>),</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"steelblue"</span>, <span class="st">"tomato"</span>),</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">bty =</span> <span class="st">"n"</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01-performance-measures_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The two classes overlap substantially, with no clear separation between A and B. This is consistent with the way the data were simulated: the predictors contain no true class signal.</p>
</section>
<section id="phase-2-k-nearest-neighbors-classification" class="level4" data-number="1.1.11.2">
<h4 data-number="1.1.11.2" class="anchored" data-anchor-id="phase-2-k-nearest-neighbors-classification"><span class="header-section-number">1.1.11.2</span> Phase 2: k-nearest neighbors classification</h4>
<p>I next use k-nearest neighbors (kNN) to classify the observations. kNN predicts the class of a new observation by finding the <span class="math inline">\(k\)</span> observations in the training data that are closest to it and assigning the class that is most common among those neighbors.</p>
<p>Because there are two predictors, the distance between two observations can be calculated using Euclidean distance:</p>
<p><span class="math display">\[
d(\mathbf{X}_i,\mathbf{X}_j)
=
\sqrt{(X_{i1}-X_{j1})^2 + (X_{i2}-X_{j2})^2}.
\]</span></p>
<p>Smaller values of <span class="math inline">\(k\)</span> make the classifier depend on fewer nearby observations, while larger values use more neighbors. I compare five possible values of <span class="math inline">\(k\)</span>:</p>
<p><span class="math display">\[
\mathcal{K} = \{1,3,5,7,9\}.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(class) <span class="co"># Loads the package containing the knn() function</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>k_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">9</span>) <span class="co"># Candidate values of k</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> sim_data[, <span class="fu">c</span>(<span class="st">"x1"</span>, <span class="st">"x2"</span>)] <span class="co"># Keeps only the predictors used by kNN</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="phase-3-choosing-k-with-cross-validation" class="level4" data-number="1.1.11.3">
<h4 data-number="1.1.11.3" class="anchored" data-anchor-id="phase-3-choosing-k-with-cross-validation"><span class="header-section-number">1.1.11.3</span> Phase 3: Choosing k with cross-validation</h4>
<p>To compare the candidate values of <span class="math inline">\(k\)</span>, I use 10-fold cross-validation. The 40 observations are divided into 10 folds, with each fold containing two observations from class A and two from class B.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">456</span>) <span class="co"># Makes the random fold assignment reproducible</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>fold_id <span class="ot">&lt;-</span> <span class="fu">integer</span>(<span class="dv">40</span>) <span class="co"># Creates a vector with one position for each observation</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>fold_id[class <span class="sc">==</span> <span class="st">"A"</span>] <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">each =</span> <span class="dv">2</span>))</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>fold_id[class <span class="sc">==</span> <span class="st">"B"</span>] <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">each =</span> <span class="dv">2</span>))</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Randomly assigns each class across 10 folds, with 2 A and 2 B per fold</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Each observation is now assigned to one of the 10 folds. During cross-validation, one fold is held out for testing while the remaining nine folds are used for training. This process is repeated until every fold has served as the test fold.</p>
<p>To compare the candidate values of <span class="math inline">\(k\)</span>, I need to store the cross-validation error calculated for each one.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>cv_error <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(k_values)) <span class="co"># Creates space to store one CV error for each value of k</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>For each candidate value of <span class="math inline">\(k\)</span>, I estimate its classification error using the 10 folds. Within each fold, the model is trained on 36 observations and tested on the 4 observations that were held out.</p>
<p>For a given fold, the classification error is the proportion of held-out observations that are classified incorrectly:</p>
<p><span class="math display">\[
\widehat{\mathrm{Err}}_{f}(k)
=
\frac{1}{n_f}
\sum_{i \in f} I(\widehat{Y}_i \neq Y_i),
\]</span></p>
<p>where <span class="math inline">\(n_f\)</span> is the number of observations in fold <span class="math inline">\(f\)</span>, and <span class="math inline">\(I(\widehat{Y}_i \neq Y_i)\)</span> equals 1 when an observation is classified incorrectly and 0 when it is classified correctly.</p>
<p>The 10-fold cross-validation error for a given value of <span class="math inline">\(k\)</span> is then the average error across the 10 folds:</p>
<p><span class="math display">\[
\widehat{\mathrm{Err}}_{\mathrm{CV}}(k)
=
\frac{1}{10}
\sum_{f=1}^{10}
\widehat{\mathrm{Err}}_{f}(k).
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (j <span class="cf">in</span> <span class="fu">seq_along</span>(k_values)) { <span class="co"># Repeats once for each candidate value of k</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  fold_error <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10</span>) <span class="co"># Stores one error for each of the 10 folds</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (fold <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>) { <span class="co"># Repeats the process for each fold</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    train_idx <span class="ot">&lt;-</span> fold_id <span class="sc">!=</span> fold <span class="co"># Observations used for training</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    test_idx  <span class="ot">&lt;-</span> fold_id <span class="sc">==</span> fold <span class="co"># Observations held out for testing</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    pred <span class="ot">&lt;-</span> <span class="fu">knn</span>(</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">train =</span> x[train_idx, ],</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">test =</span> x[test_idx, ],</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">cl =</span> class[train_idx],</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">k =</span> k_values[j]</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    fold_error[fold] <span class="ot">&lt;-</span> <span class="fu">mean</span>(pred <span class="sc">!=</span> class[test_idx]) <span class="co"># Error in the held-out fold</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  cv_error[j] <span class="ot">&lt;-</span> <span class="fu">mean</span>(fold_error) <span class="co"># Average error across all 10 folds</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>For each candidate value of <span class="math inline">\(k\)</span>, the model is evaluated across all 10 folds. The errors from the 10 folds are then averaged to produce one cross-validation error for that value of <span class="math inline">\(k\)</span>. This process is repeated for each candidate value of <span class="math inline">\(k\)</span>.</p>
<p>I combine the candidate values of <span class="math inline">\(k\)</span> and their corresponding cross-validation errors into a table so that their performance can be compared directly.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>cv_results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">k =</span> k_values,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">cv_error =</span> cv_error</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>) <span class="co"># Combines each candidate k with its corresponding 10-fold CV error</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>cv_results <span class="co"># Shows the CV error for each k</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  k cv_error
1 1    0.525
2 3    0.425
3 5    0.525
4 7    0.525
5 9    0.575</code></pre>
</div>
</div>
<p>Among the five candidate values, k = 3 has the lowest cross-validation error at 0.425, meaning that 42.5% of the held-out observations were misclassified on average.</p>
<p>I select the value of <span class="math inline">\(k\)</span> with the smallest cross-validation error. This can be written as</p>
<p><span class="math display">\[
k^*
=
\underset{k \in \mathcal{K}}{\arg\min}
\ \widehat{\mathrm{Err}}_{\mathrm{CV}}(k).
\]</span></p>
<p>Here, <span class="math inline">\(k^*\)</span> represents the value of <span class="math inline">\(k\)</span> that appears to perform best according to cross-validation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>best_index <span class="ot">&lt;-</span> <span class="fu">which.min</span>(cv_error) <span class="co"># Finds the position of the smallest CV error</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>best_k <span class="ot">&lt;-</span> k_values[best_index] <span class="co"># Uses that position to identify the corresponding k</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>best_k</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>min_cv_error <span class="ot">&lt;-</span> <span class="fu">min</span>(cv_error) <span class="co"># Stores the lowest 10-fold CV error across all candidate k values</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>min_cv_error</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.425</code></pre>
</div>
</div>
<p>For this particular simulated dataset, cross-validation selects k = 3, with a minimum estimated error of 42.5%.</p>
</section>
<section id="phase-4-nested-cross-validation" class="level4" data-number="1.1.11.4">
<h4 data-number="1.1.11.4" class="anchored" data-anchor-id="phase-4-nested-cross-validation"><span class="header-section-number">1.1.11.4</span> Phase 4: Nested cross-validation</h4>
<p>The minimum cross-validation error calculated above is based on the same cross-validation procedure that was used to choose <span class="math inline">\(k\)</span>. Because the best-performing value is selected from several candidates, this minimum error may make the classifier appear better than it really is.</p>
<p>To separate model selection from model evaluation, I next use nested cross-validation. The procedure has two levels:</p>
<ol type="1">
<li>The <strong>inner cross-validation</strong> chooses the best value of <span class="math inline">\(k\)</span>.</li>
<li>The <strong>outer cross-validation</strong> evaluates the classifier using an observation that was not involved in choosing <span class="math inline">\(k\)</span>.</li>
</ol>
<p>In this simulation, the outer procedure uses leave-one-out cross-validation (LOOCV). One of the 40 observations is held out, leaving 39 observations for model selection. Ten-fold cross-validation is then performed using only those 39 observations to choose <span class="math inline">\(k\)</span>. The selected value of <span class="math inline">\(k\)</span> is used to predict the single untouched outer observation.</p>
<p>This process is repeated until every observation has been held out once.</p>
<p><strong>Illustration:</strong> How nested cross-validation works</p>
<p>The diagram below shows how the inner and outer stages work together.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A["Start with 40 observations"] --&gt; B["Outer loop: hold out 1 observation"]
    B --&gt; C["Use the remaining 39 observations as training data"]
    C --&gt; D["Inner loop: perform 10-fold cross-validation on the 39 observations"]
    D --&gt; E["Compare candidate values of k"]
    E --&gt; F["Choose the best k"]
    F --&gt; G["Train kNN on all 39 observations using the chosen k"]
    G --&gt; H["Predict the 1 held-out observation"]
    H --&gt; I["Record whether the prediction was correct or incorrect"]
    I --&gt; J["Repeat until every observation has been held out once"]
    J --&gt; K["Average the 40 outer prediction errors"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Because the same 10-fold cross-validation procedure is used whenever I need to compare candidate values of <span class="math inline">\(k\)</span>, I place this repeated computation inside a reusable function. The function takes a training dataset, evaluates all candidate values of <span class="math inline">\(k\)</span>, and returns both the selected <span class="math inline">\(k\)</span> and its minimum cross-validation error.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>select_k_cv <span class="ot">&lt;-</span> <span class="cf">function</span>(x_train, y_train, k_values) { <span class="co"># Uses 10-fold CV to compare candidate values of k</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  fold_id <span class="ot">&lt;-</span> <span class="fu">integer</span>(<span class="fu">length</span>(y_train)) <span class="co"># Creates one fold label per training observation</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  fold_id[y_train <span class="sc">==</span> <span class="st">"A"</span>] <span class="ot">&lt;-</span> <span class="fu">sample</span>(</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">length.out =</span> <span class="fu">sum</span>(y_train <span class="sc">==</span> <span class="st">"A"</span>))</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  fold_id[y_train <span class="sc">==</span> <span class="st">"B"</span>] <span class="ot">&lt;-</span> <span class="fu">sample</span>(</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">length.out =</span> <span class="fu">sum</span>(y_train <span class="sc">==</span> <span class="st">"B"</span>))</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Distributes observations from each class approximately evenly across the 10 folds</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  cv_error <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(k_values)) <span class="co"># Stores one CV error for each candidate k</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="fu">seq_along</span>(k_values)) { <span class="co"># Tries each candidate value of k</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    observation_error <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(y_train)) <span class="co"># Stores prediction errors for this k</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (fold <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>) { <span class="co"># Uses each fold once for testing</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>      train_idx <span class="ot">&lt;-</span> fold_id <span class="sc">!=</span> fold <span class="co"># Observations used for training</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>      test_idx <span class="ot">&lt;-</span> fold_id <span class="sc">==</span> fold <span class="co"># Observations held out for testing</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>      pred <span class="ot">&lt;-</span> <span class="fu">knn</span>(</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>        <span class="at">train =</span> x_train[train_idx, , <span class="at">drop =</span> <span class="cn">FALSE</span>],</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>        <span class="at">test =</span> x_train[test_idx, , <span class="at">drop =</span> <span class="cn">FALSE</span>],</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>        <span class="at">cl =</span> y_train[train_idx],</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>        <span class="at">k =</span> k_values[j]</span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>      observation_error[test_idx] <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>        pred <span class="sc">!=</span> y_train[test_idx]</span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>      ) <span class="co"># Records 1 for an incorrect prediction and 0 for a correct prediction</span></span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>    cv_error[j] <span class="ot">&lt;-</span> <span class="fu">mean</span>(observation_error) <span class="co"># Calculates CV error for this k</span></span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(</span>
<span id="cb16-41"><a href="#cb16-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">best_k =</span> k_values[<span class="fu">which.min</span>(cv_error)], <span class="co"># k with the lowest CV error</span></span>
<span id="cb16-42"><a href="#cb16-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_cv_error =</span> <span class="fu">min</span>(cv_error) <span class="co"># Corresponding minimum CV error</span></span>
<span id="cb16-43"><a href="#cb16-43" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-44"><a href="#cb16-44" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The outer leave-one-out procedure is also repeated whenever nested cross-validation is performed. I therefore place this procedure inside a reusable function. For each held-out observation, the function uses <code>select_k_cv()</code> on the remaining observations to choose <span class="math inline">\(k\)</span>, predicts the untouched observation, and finally averages the outer prediction errors.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>nested_cv_once <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y, k_values) { <span class="co"># Runs nested CV on one dataset</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  nested_error <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(y)) <span class="co"># Stores one outer prediction error per observation</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(y)) { <span class="co"># Holds out each observation once</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    outer_train_idx <span class="ot">&lt;-</span> <span class="fu">seq_along</span>(y) <span class="sc">!=</span> i <span class="co"># The remaining 39 observations</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    outer_test_idx <span class="ot">&lt;-</span> <span class="fu">seq_along</span>(y) <span class="sc">==</span> i <span class="co"># The one untouched observation</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    x_outer <span class="ot">&lt;-</span> x[outer_train_idx, , drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    y_outer <span class="ot">&lt;-</span> y[outer_train_idx]</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    inner_result <span class="ot">&lt;-</span> <span class="fu">select_k_cv</span>(</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">x_train =</span> x_outer,</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">y_train =</span> y_outer,</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">k_values =</span> k_values</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    ) <span class="co"># Chooses k using only the 39 outer-training observations</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>    best_inner_k <span class="ot">&lt;-</span> inner_result<span class="sc">$</span>best_k <span class="co"># Extracts the selected k</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>    pred_outer <span class="ot">&lt;-</span> <span class="fu">knn</span>(</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">train =</span> x_outer,</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">test =</span> x[outer_test_idx, , <span class="at">drop =</span> <span class="cn">FALSE</span>],</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">cl =</span> y_outer,</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">k =</span> best_inner_k</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>    ) <span class="co"># Predicts the untouched outer observation</span></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>    nested_error[i] <span class="ot">&lt;-</span> pred_outer <span class="sc">!=</span> y[outer_test_idx]</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Records whether the outer prediction was incorrect</span></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(nested_error) <span class="co"># Returns the average error across all outer predictions</span></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>I now apply the nested cross-validation procedure to the original 40-observation dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">789</span>) <span class="co"># Makes the inner CV fold assignments reproducible</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>nested_cv_error <span class="ot">&lt;-</span> <span class="fu">nested_cv_once</span>(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> x,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> class,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">k_values =</span> k_values</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>) <span class="co"># Runs nested CV on the original simulated dataset</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>nested_cv_error</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.65</code></pre>
</div>
</div>
<p>The nested cross-validation error for this particular simulated dataset is 65%. Unlike the minimum ordinary cross-validation error, this estimate is based on outer observations that were not used to choose <span class="math inline">\(k\)</span>, so model selection and model evaluation are kept separate.</p>
</section>
<section id="phase-5-evaluating-on-an-independent-test-set" class="level4" data-number="1.1.11.5">
<h4 data-number="1.1.11.5" class="anchored" data-anchor-id="phase-5-evaluating-on-an-independent-test-set"><span class="header-section-number">1.1.11.5</span> Phase 5: Evaluating on an independent test set</h4>
<p>Nested cross-validation provides an estimate of model performance using only the original 40 observations. However, because the data are simulated, I can also generate a large independent test set that was never used for training or model selection.</p>
<p>In the null setting, the predictors contain no true class information, so the expected classification error on new observations is approximately 50%. I therefore use the independent test set as a benchmark for the error estimates obtained from cross-validation.</p>
<p>I generate 20,000 new observations using the same data-generating process as before, with 10,000 observations from class A and 10,000 from class B.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">999</span>) <span class="co"># Makes the independent test set reproducible</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>test_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>), <span class="at">each =</span> <span class="dv">10000</span>)) <span class="co"># Creates 20,000 balanced class labels</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>test_x <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">x1 =</span> <span class="fu">rnorm</span>(<span class="dv">20000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">x2 =</span> <span class="fu">rnorm</span>(<span class="dv">20000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>) <span class="co"># Generates two predictors with no true class signal</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The model is then trained on all 40 original observations using the value of <span class="math inline">\(k\)</span> selected by ordinary cross-validation. It is evaluated on the 20,000 new observations.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>test_pred <span class="ot">&lt;-</span> <span class="fu">knn</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">train =</span> x,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">test =</span> test_x,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">cl =</span> class,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">k =</span> best_k</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>) <span class="co"># Predicts the classes of the independent test observations</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The independent test-set error is the proportion of the 20,000 predictions that are incorrect:</p>
<p><span class="math display">\[
\widehat{\mathrm{Err}}_{\mathrm{test}}
=
\frac{1}{20000}
\sum_{i=1}^{20000}
I(\widehat{Y}_i^{\mathrm{test}} \neq Y_i^{\mathrm{test}}).
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>test_error <span class="ot">&lt;-</span> <span class="fu">mean</span>(test_pred <span class="sc">!=</span> test_class) <span class="co"># Proportion of independent test observations classified incorrectly</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>test_error</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.498</code></pre>
</div>
</div>
<p>Because the independent test observations were not involved in either training or selecting <span class="math inline">\(k\)</span>, this error provides a benchmark for how the selected classifier performs on new data.</p>
</section>
<section id="phase-6-repeating-the-simulation" class="level4" data-number="1.1.11.6">
<h4 data-number="1.1.11.6" class="anchored" data-anchor-id="phase-6-repeating-the-simulation"><span class="header-section-number">1.1.11.6</span> Phase 6: Repeating the simulation</h4>
<p>The results above are based on a single simulated dataset. Because a different random sample of 40 observations could produce different cross-validation errors, I repeat the entire simulation many times to examine the behavior of each error estimate across repeated samples.</p>
<p>For each repetition, I generate a new dataset of 40 observations and repeat the same three evaluations:</p>
<ol type="1">
<li>Select <span class="math inline">\(k\)</span> using ordinary 10-fold cross-validation and record the minimum CV error.</li>
<li>Estimate error using nested cross-validation.</li>
<li>Evaluate the selected model on a new independent test set of 20,000 observations.</li>
</ol>
<p>Because the cross-validation procedures were defined as reusable functions in Phase 4, I can apply them directly to each new simulated dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>run_one_simulation <span class="ot">&lt;-</span> <span class="cf">function</span>() { <span class="co"># Runs the entire experiment once</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>), <span class="at">each =</span> <span class="dv">20</span>))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Creates 40 balanced class labels: 20 A and 20 B</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  x_sim <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x1 =</span> <span class="fu">rnorm</span>(<span class="dv">40</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x2 =</span> <span class="fu">rnorm</span>(<span class="dv">40</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="co"># Generates a new null dataset</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  ordinary <span class="ot">&lt;-</span> <span class="fu">select_k_cv</span>(</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x_train =</span> x_sim,</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y_train =</span> y,</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">k_values =</span> k_values</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="co"># Runs ordinary 10-fold CV on all 40 observations</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>  nested_error <span class="ot">&lt;-</span> <span class="fu">nested_cv_once</span>(</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> x_sim,</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> y,</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">k_values =</span> k_values</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="co"># Estimates error using nested cross-validation</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>  test_y <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>), <span class="at">each =</span> <span class="dv">10000</span>))</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Creates 20,000 balanced labels for independent testing</span></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>  test_x <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">x1 =</span> <span class="fu">rnorm</span>(<span class="dv">20000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">x2 =</span> <span class="fu">rnorm</span>(<span class="dv">20000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="co"># Generates a new independent test set</span></span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>  test_pred <span class="ot">&lt;-</span> <span class="fu">knn</span>(</span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">train =</span> x_sim,</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">test =</span> test_x,</span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">cl =</span> y,</span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">k =</span> ordinary<span class="sc">$</span>best_k</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>  ) <span class="co"># Uses the k selected by ordinary CV</span></span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a>  test_error <span class="ot">&lt;-</span> <span class="fu">mean</span>(test_pred <span class="sc">!=</span> test_y)</span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculates the independent test-set error</span></span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(</span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_cv_error =</span> ordinary<span class="sc">$</span>min_cv_error,</span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">nested_cv_error =</span> nested_error,</span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">test_error =</span> test_error</span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a>  ) <span class="co"># Returns the three error estimates</span></span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="repeating-the-experiment-500-times" class="level5" data-number="1.1.11.6.1">
<h5 data-number="1.1.11.6.1" class="anchored" data-anchor-id="repeating-the-experiment-500-times"><span class="header-section-number">1.1.11.6.1</span> Repeating the experiment 500 times</h5>
<p>I now repeat the complete simulation 500 times. Each repetition generates a new training dataset and a new independent test set, allowing the three error estimates to be compared across repeated random samples.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>) <span class="co"># Makes the complete repeated simulation reproducible</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>sim_results <span class="ot">&lt;-</span> <span class="fu">replicate</span>(</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="dv">500</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">run_one_simulation</span>()</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>) <span class="co"># Runs the entire experiment 500 times</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>sim_results <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">t</span>(sim_results))</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Converts the results so that each row represents one simulation</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># and each column represents one error-estimation method</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sim_results) <span class="co"># Displays the first six simulation results</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  min_cv_error nested_cv_error test_error
1        0.425           0.450    0.49910
2        0.525           0.625    0.49565
3        0.200           0.200    0.50090
4        0.450           0.650    0.49925
5        0.550           0.675    0.50040
6        0.275           0.350    0.50140</code></pre>
</div>
</div>
</section>
</section>
<section id="simulation-results" class="level4" data-number="1.1.11.7">
<h4 data-number="1.1.11.7" class="anchored" data-anchor-id="simulation-results"><span class="header-section-number">1.1.11.7</span> Simulation results</h4>
<p>To compare the three error estimates across the 500 simulations, I first calculate their average values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colMeans</span>(sim_results) <span class="co"># Calculates the average error for each method across all 500 simulations</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   min_cv_error nested_cv_error      test_error 
      0.4210000       0.5126500       0.4998129 </code></pre>
</div>
</div>
<p>I also compare the full distributions of the three error estimates. The dashed horizontal line represents the expected 50% classification error in the null setting.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  sim_results<span class="sc">$</span>min_cv_error,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  sim_results<span class="sc">$</span>nested_cv_error,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  sim_results<span class="sc">$</span>test_error,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"Minimum CV"</span>, <span class="st">"Nested CV"</span>, <span class="st">"Independent test"</span>),</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Classification error"</span>,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Error Estimates Across 500 Simulations"</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>) <span class="co"># Compares the distributions of the three error estimates</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fl">0.50</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="co"># Expected 50% error under the null</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01-performance-measures_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="conclusions" class="level3" data-number="1.1.12">
<h3 data-number="1.1.12" class="anchored" data-anchor-id="conclusions"><span class="header-section-number">1.1.12</span> Conclusions</h3>
<p>Across 500 simulated null datasets, the minimum ordinary cross-validation error averaged 42.1%, while the independent test-set error averaged 49.98%. This shows that reporting the minimum CV error after tuning made the classifier appear more accurate than it actually was on new data.</p>
<p>Nested cross-validation produced an average error of 51.27%, which was much closer to the independent test-set error. This supports the main point of Varma and Simon (2006): when cross-validation is used both to tune a model and to report its performance, the minimum CV error can be optimistically biased. In this simulation, nested cross-validation provided an estimate closer to the independent test-set error.</p>
<p>In this small-sample simulation, nested cross-validation was also more variable across repetitions. Its main advantage here was therefore reducing bias rather than producing a more stable estimate.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Preface">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>